name: Gentoo Stage1 For x86_64

#on:
#  schedule:
#  - cron: ""

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clean up disk space
      run: |
        set -x
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi $(docker images -q)
        sudo apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo apt autoremove --purge -y

    - name: Initialization environment
      run: |
        set -x
        [ -f sources.list ] && (
          sudo cp -rf sources.list /etc/apt/sources.list
          sudo rm -rf /etc/apt/sources.list.d/* /var/lib/apt/lists/*
          sudo apt-get clean
        )
        sudo apt-get update
        sudo apt install wget curl rsync xz-utils tar git -y
        sudo apt autoremove --purge -y
        sudo apt-get clean
        sudo timedatectl set-timezone Asia/Shanghai
        sudo mkdir -pv /mnt/gentoo
    - name: Download and Install Stage3 Files
      run: |
        set -x
        MIRRORS='https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds'
        FILENAME=`curl -L $MIRRORS/latest-stage3.txt  2>/dev/null |grep ^[0-9]|awk '{if (NR==1) {print $1}}'`
        FILEURL="$MIRRORS/$FILENAME"
        cd /mnt/gentoo ;sudo wget -c  $FILEURL
        sudo tar xvJpf stage3-amd64-*.tar.xz --xattrs-include='*.*' --numeric-owner
        cd; git clone https://github.com/slmoby/gentoo-ci/
        sudo cp ~/gentoo-ci/dotfiles/etc/portage/make.conf /mnt/gentoo/etc/portage/make.conf
        sudo mkdir -pv /mnt/gentoo/etc/portage/repos.conf
        sudo cp -v ~/gentoo-ci/dotfiles/etc/portage/repos.conf/gentoo.conf /mnt/gentoo/etc/portage/repos.conf
        sudo cp -rv ~/gentoo-ci/dotfiles/etc/portage/package.use/ /mnt/gentoo/etc/portage
        sudo cp -rv ~/gentoo-ci/dotfiles/etc/portage/env /mnt/gentoo/etc/portage
        sudo cp -rv ~/gentoo-ci/dotfiles/etc/portage/package.env/ /mnt/gentoo/etc/portage
        sudo cp -v ~/gentoo-ci/dotfiles/etc/fstab /mnt/gentoo/etc/fstab
        sudo cp -v ~/gentoo-ci/script/bootstrap.sh /mnt/gentoo/root/bootstrap.sh
    - name: chroot environment
      run: |
        set -x
        sudo cp -v -L /etc/resolv.conf /mnt/gentoo/etc/
        sudo mount -v -t proc none /mnt/gentoo/proc
        sudo mount -v --rbind /sys /mnt/gentoo/sys
        sudo mount -v --rbind /dev /mnt/gentoo/dev
        sudo mount -v --make-rslave /mnt/gentoo/sys
        sudo mount -v --make-rslave /mnt/gentoo/dev
        sudo test -L /dev/shm &&  sudo rm /dev/shm &&  sudo mkdir /dev/shm
        sudo mount --types tmpfs --options nosuid,nodev,noexec shm /dev/shm
        sudo chmod 1777 /dev/shm
    - name: build stage1
      run: |
        set -x
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;mount -a"
    - name: rewrite gentoo.conf
      run: |
        set -x 
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;mkdir -pv /var/db/repos/gentoo; "
        sudo chroot /mnt/gentoo /bin/bash -c "wget -qO- https://github.com/gentoo-mirror/gentoo/archive/stable.tar.gz | tar zx --directory /var/db/repos/gentoo --strip-component=1"
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;emerge -v  dev-vcs/git" 
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;cd ;git clone https://github.com/slmoby/gentoo-ci"
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;rm -f /etc/portage/repos.conf/gentoo.conf"   
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;rm -rf  /var/db/repos/gentoo"    
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;cd;cp gentoo-ci/gentoo.conf /etc/portage/repos.conf/gentoo.conf"
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;emaint sync --auto"
    - name: notmpfs
      run: |
        set -x
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;mkdir -pv /var/tmp/notmpfs"


    - name: timezone
      run: | 
        set -x 
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;echo "Asia/Shanghai" > /etc/timezone"
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;emerge -v --config sys-libs/timezone-data"
    - name: locale
      run: | 
        set -x
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen"
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gent"
        sudo chroot /mnt/gentoo /bin/bash -c  "source /etc/profile;locale-gen"
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;eselect locale set  3"
    - name: bootstrap stage1
      run: |
        set -x
        sudo chroot /mnt/gentoo /bin/bash -c "source /etc/profile;cd  ;bash bootstrap.sh"


    - name: Make the product
      run: |
        cd
        mkdir -pv output
        mkdir -pv tmp
        sudo rsync -aAXv --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} ./tmp
        cd ./tmp;sudo tar -jcvf ../output/stage1.tar.bz2 .
    - name: Stage1  packages
      uses: actions/upload-artifact@master
      with:
        name: Stage1 Files
        path: output/stage1.tar.bz2
